"""empty message

Revision ID: 2c35502dbee3
Revises: 89e9116e8b29
Create Date: 2025-04-30 22:04:14.348222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c35502dbee3'
down_revision = '89e9116e8b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_people', ['user_id', 'people_id'])

    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_planet', ['user_id', 'planet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_planet', type_='unique')

    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_people', type_='unique')

    # ### end Alembic commands ###
